In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('startup_funding.csv')
df.head(5)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [4]:
df['Startup Name'].unique().tolist()

['BYJU’S',
 'Shuttl',
 'Mamaearth',
 'https://www.wealthbucket.in/',
 'Fashor',
 'Pando',
 'Zomato',
 'Ecozen',
 'CarDekho',
 'Dhruva Space',
 'Rivigo',
 'Healthians',
 'Licious',
 'InCred',
 'Trell',
 'Rein Games',
 'Lenskart.com',
 'Freshworks',
 'Misters',
 'Sunstone Eduversity Pvt. Ltd',
 'Burger Singh',
 'Ninjacart',
 'Aye Finance',
 'SuperGaming',
 'Clumio',
 'eBikeGo',
 'Digital Mall Asia',
 'Medikabazaar',
 'Vogo Automotive',
 'Furtados School of Music',
 'Paytm',
 'Dunzo',
 'Udaan',
 'The Man Company',
 'FPL Technologies',
 'Cashflo',
 'Digital F5',
 '3rdFlix',
 '75F',
 'Myelin Foundry',
 'Atomberg Technology',
 'GOQii',
 'Vyapar App',
 'Progcap',
 'MyPetrolPump',
 'Alteria Capital',
 'Pine Labs',
 'Meesho',
 'Cars24',
 'Uniphore',
 'Zendrive',
 'Lo! Foods',
 'Tala',
 'INDwealth',
 'HungerBox',
 'AdmitKard',
 'Mishry Reviews',
 'Grofers',
 'Rapido Bike Taxi',
 'RenewBuy',
 'Atlan',
 'WizCounsel',
 'Ola Cabs',
 'Daalchini Technologies',
 '"BYJU\\\\\'S"',
 'Moglix',
 'Ezyhaul',
 'Indus OS',
 'HealthAssure',
 'House of Msasaba',
 'Board Infinity',
 'NoBroker',
 'Bira91',
 'FabHotels',
 'Avail Finance',
 'BharatPe',
 'Recykal',
 'Agara Labs',
 'Sistema.bio',
 'Chakr Innovation',
 'Pratilipi',
 'Bolo App',
 'OkCredit',
 'Biz2Credit',
 'Vogo Automotive Pvt. Ltd.',
 'Leegality',
 'Ola Electric',
 'Saahas Zero Waste',
 'StyleDotMe',
 'BlackBuck',
 'Zenoti',
 'Ather Energy',
 'FreshVnF',
 'GlowRoad',
 'Kuvera',
 'Medlife',
 'Kabadiwala',
 'Tripoto',
 'Azah',
 'Setu',
 'Toppr',
 'Craftsvilla',
 'Unacademy',
 'CleverTap',
 'My Healthcare',
 'KrazyBee',
 'Increff',
 'FleetX',
 'Zilingo',
 'NanoClean Global',
 'OyoRooms',
 'Vyome Therapeutics Inc.',
 'Samunnati Financial Intermediation & Services Pvt. Ltd',
 'Manch',
 'UrbanClap Technologies Pvt. Ltd',
 'Guiddoo',
 'Career Anna',
 'Nagpur Wholesale',
 'ShopKirana',
 'BuildSupply',
 'GoDesi',
 'Veritas Finance Ltd.',
 'Mobile Premier League',
 'A&R Bon Vivants',
 'Blackbuck',
 'MilkBAsket',
 'DriveU',
 'CleanseCar',
 'Automation Anywhere',
 'HealthifyMe',
 'Genius Corner',
 'Aavishkaar-Intellecap Group',
 'Skillbox',
 'Signzy',
 'Engineer.ai',
 'InCred Finance',
 'Roposo',
 'Northmist',
 'Origo Commodities India Pvt. Ltd',
 'Grover Zampa',
 'Droom',
 'Innov8',
 'LetsTransport',
 'Netmeds',
 'Daily hunt',
 '3HCare',
 'HappyGoEasy',
 'Nykaa',
 'Mad Street Den',
 'Dream11',
 'MamaEarth',
 'AutoGrid',
 'Pharmeasy',
 'Upwards',
 'Kissht',
 'dishq',
 'HealthFin',
 'Samosa Labs',
 'ZiffyHomes',
 'My OmNamo',
 'ShopX',
 'MakeMyTrip',
 'Hansel io',
 'Metro Bikes',
 'Phone Pe',
 'quizizz',
 'Happy EMI',
 'Inthree',
 'Observe AI',
 'Enakshi',
 'EazyDiner',
 'Finzy',
 'RawPressery',
 'Pi Ventures',
 'Revv',
 'ZestMoney',
 'Shubh Loans',
 'MyUpchar',
 'Narvar',
 'True North',
 'Leena AI',
 'Biryani By Kilo',
 'Anchanto',
 'Loan Tap',
 'PolicyBazaar',
 'zippserv',
 'Groww',
 'Avenue Growth',
 'iNICU',
 'Kinara Capital',
 'Shop 101',
 'Sambandh',
 '19th mile',
 '5th Vital',
 'MEngage',
 'Ofbusiness',
 'The Ken',
 'Book My Show',
 'HousingMan',
 'PaySense',
 'Yulu Bikes',
 'VTION',
 'Log9 Materials',
 'kidovators',
 'Digit',
 'Black Soil',
 'iqlect',
 'Entropik',
 'Bitla Software',
 'TheCapitalNet',
 'Cure Fit',
 'Five Star Group',
 'Healthsignz',
 'CoinTribe',
 'Digiconectt',
 'Kashmir Box',
 'Crowdera',
 'Zoctr',
 'Annapurna Finance',
 'AyeFinance',
 'Theranosis',
 'Alpha Capital',
 'eshakti',
 'Daily Ninja',
 'NirogStreet',
 'Nivesh',
 'What\\\\xe2\\\\x80\\\\x99s Up Life',
 'HomeLane',
 'Network Intelligence',
 'Tynor Othontics',
 'Elucidata',
 'Chrysalis',
 'RentSher',
 'Drip capital',
 'WickedRide',
 'HipBar',
 'Sqqrl',
 'Sigtuple',
 'Wow Express',
 'Front Desk AI',
 'Edureka',
 'Numeroseven',
 'OpenTap',
 'Bizongo',
 'Disprz',
 'PaisaDukan',
 'i3sysytems',
 'Earth Food',
 'mfine',
 'Rocketium',
 'MilkBasket',
 'Vola',
 'Cashkumar',
 'Edyoo',
 'Aashiyaan',
 'Smartivity',
 'Bonphulapl',
 'Acko',
 'HWell24',
 'Toffee',
 'Tonetag',
 'Events High',
 'Stellaps',
 'Credright',
 'Fitternity',
 'Synctag',
 'Benepik',
 'Varthana',
 'IndigoLearn',
 'Vedantu',
 'Kaleidofin',
 'Pipabella',
 'Elemential',
 'Kriger Campus',
 'Loanzen',
 'TravelTriangle',
 'Letsmd',
 'mintifi',
 'icanstay',
 'Pregbuddy',
 'Coverfox',
 'Lenskart',
 'mamaearth',
 'Fyle Technologies',
 'True Balance',
 'Visit',
 'Doxper',
 'Mihuru',
 'Capital Float',
 'Trip shelf',
 'POPxo',
 'RailYatri',
 '1mg',
 'Rubique',
 'Samco',
 'MyLoanCare',
 'PharmEasy',
 'Buddy4studdy',
 'Urban Ladder',
 'Gramophone',
 'Wellthy',
 'MedGenome',
 'Finova Capital',
 'Hotelogix',
 'Livehealth',
 'Ad2pro',
 'Pepperfry',
 'Magicpin',
 'HealthCare',
 'PineLabs',
 'Stumagz',
 'AvailFinance',
 'Fingerlix',
 'Karma Healthcare',
 'Zappfresh',
 'CustomerSucessBox',
 'One Labs',
 'GigIndia',
 'Chargebee',
 'i2i Funding',
 'Slang Labs',
 'UrbanPiper',
 'Cash Suvidha',
 'Roadcast',
 'Smartcoin',
 'The Print',
 'Fynd',
 'BigBasket',
 'Asia Institute Of Medical Science',
 'CollegeDekho',
 'Foodmemories',
 'Healthi',
 'Swiggy',
 'Shape',
 'Icertis',
 'healthifyme',
 'MedTel',
 'Rupeek',
 'WebEngage',
 'Lendingkart',
 'Wydr',
 'Cashify',
 'holachef',
 'Awaaz De',
 'IMAX Program',
 'Littlemore',
 'Shirsa Labs',
 'MoneyOnMobile',
 'PetSutra',
 'Infibeam',
 'happay',
 'Fincash',
 'Agricxlab',
 'Capillary',
 'The Healthy Billions',
 'HighRadius',
 'Avishkaar Box',
 'Planys Technologies',
 'Lollypop',
 'Trilyo',
 'Gaana',
 'Credy',
 'Predible Health',
 'EarlySalary',
 'WOTU',
 'DAAKI',
 'Kinsane Entertainment Inc',
 'Tapzo',
 'Appario Retail Pvt Ltd.',
 'Samunnati',
 'Sahajanand Medical Technologies',
 'Kuants',
 'Razorpay',
 'Streak',
 'pi Ventures',
 'Newgen Software',
 'Rubix',
 'ShareChat',
 'Paperflite',
 'Skillate',
 'OptaCredit',
 'AEON Learning',
 'Milkbasket',
 'NeoGrowth Credit',
 'Rao IIT Academy',
 'Glassic',
 'GreyAtom',
 'Axio',
 'eKincare',
 'The Wedding Brigade',
 'PeeSafe',
 'BrowserStack',
 'Scapic',
 'CureFit',
 'iNurture',
 'Strata Enviro',
 'Tata Housing',
 'HandyTrain',
 'Mobycy',
 'Greenlight Planet',
 'Fintobox',
 'Mswipe',
 'The Label Life',
 'Cygnus Hospitals',
 'eShakti',
 'Inshorts',
 'Vahdam Tea',
 'Logic Roots',
 'Project Mudra',
 'Furlenco',
 'I Can Stay',
 'Fracktal Works',
 'Simility',
 'Shopholix',
 'MindTickle',
 'Nazara Technologies',
 'DocsApp',
 'Capita World',
 'Tea Box',
 'Transversal Technologies',
 'Curofy',
 'WeDoSky',
 'Purplle',
 'Sky Met Weather',
 'Springboard',
 'Peel Works',
 '9Stacks',
 'Your Quote',
 'Spandana Sphoorty',
 'EasyEcom',
 'IGP.com',
 'Specsmakers',
 'Garage On Road',
 'Foyr.com',
 'Prest Loans',
 'AadharAPI.com',
 'FreshBoxx',
 'Vagupu',
 'HalaPlay',
 'Kalpnik Technologies',
 'Hevo Data',
 'Smart Karma',
 'Leverage Edu',
 'Crayon Data',
 'DocTalk',
 'CoveIoT',
 'TalentEdge',
 'Fisdom',
 'FarmLink',
 'OpenApp',
 'NoPaperForms',
 'Tilite Technologies Pvt. Ltd',
 'Mobiliz AR',
 'Qubole',
 'Happily Unmarried',
 'Universal Sportsbiz Pvt. Ltd',
 'Hungry Foal',
 'Active AI',
 'Sumeru',
 'ElderAid Wellness',
 'Omnia Information',
 'Josh Talks',
 'Reniso',
 'Kanhaiya',
 'Perspectico',
 'ONN Bikes',
 'Rapido',
 'Heckyl',
 'Nuvepro',
 'RedBook',
 'Portea',
 'Credit Mate',
 'Epiq Capital',
 'MiStay',
 'WittyFeed',
 'IDG Ventures',
 'TempGo',
 'Edelweiss',
 'ERA',
 'Smaaash',
 'Chumbak',
 'FR8',
 'MobieFit',
 'Stanza Living',
 'ChqBook',
 'HomeCapital',
 'Elanic',
 'CollPoll',
 'PhonePe',
 'Little Black Book',
 'Oorjan',
 'Zefo',
 'Yaantra',
 'Farm Taaza',
 'Drivezy',
 'Slice Pay',
 'Agrowave',
 'MyGubbi',
 'IBSFintech',
 'Letsservice',
 'OneStepUp',
 'ThirdWatch',
 'Parallel Dots',
 'Easy Diner',
 'StanPlus',
 'UCLID',
 'Policy Bazaar',
 'Gapoon',
 'Chaayos',
 'Renew Buy',
 'Bank Bazaar',
 'Hasura',
 'LenDen Club',
 'RAW Pressery',
 'Cashe',
 'Park Easy',
 'TagBox',
 'FYRE',
 'ZipLoan',
 'Skillenza',
 'Chevon',
 'PropStory',
 'SpotDraft',
 'Big Basket',
 'OfBusiness',
 'Olly Credit',
 'CashFree',
 'GoldFarm',
 'NetMeds',
 'MSE',
 'Aahaa Stores',
 'MFine',
 'Canvera',
 'PrimaryIO',
 'Nest Education',
 'Lending Kart',
 'GoFro',
 'OncoStem',
 'Power2SME',
 'Credit Vidya',
 'Tails Life',
 'OYO Rooms',
 'Early Salary',
 'Seniority',
 'AYE Finance',
 'Farmizen',
 'Ecom Express',
 'Call Health',
 'Sattviko',
 'Tonbo Imaging',
 'Get My Parking',
 'Glowroad',
 'Heterogenous',
 'Gurukul',
 'WheelStreet',
 'Xprep',
 'The Moms Co',
 'Noticeboard',
 'High Radius',
 'HWell24 Plus',
 'SaveBC',
 'Gaming Monk',
 '91SpringBoard',
 'Homergize',
 'Yatra.com',
 'Ace Turtle',
 'Vogo',
 'Synup',
 'Tinmen',
 'Cropin',
 'Sportobuddy',
 'Credifiable',
 'Inclov',
 'Multibhashi',
 'Transerve',
 'Fashalot',
 'Pitstop',
 'GoChoppers',
 'Aadyah',
 'TouchKin',
 'Ethinos',
 'Zepo',
 'Click2Clinic',
 'SpeedBox',
 'Skill Connect',
 'Chai Point',
 'Lime Tray',
 'CoutLoot',
 'Box My Space',
 'Curatio',
 'New Castle Technologies',
 'My Forex Eye',
 'TruxApp',
 'CroFarm',
 'DoodhWala',
 'Stayabode',
 'Flipkart',
 'Moong Labs',
 'Sports Flashes',
 'Digilend',
 'KNAB Finance',
 'Get Simpl',
 'Rootefy',
 'Cerebroz',
 'Flochat',
 'EasyGov',
 'Milk Basket',
 'Dhruva',
 'Bombay Shaving Company',
 'Awign',
 'Indiez',
 'Ezetap',
 'Ink Monk',
 'Medinfi',
 'Mobikon',
 'Fieldassist',
 'Treebo',
 'Billion Loans',
 'Ecolibriumenergy',
 'Jumbotail',
 'Timesaverz',
 'Minjar',
 'MyCity4kids',
 'Clip App',
 'Upwardly.in',
 'Autorox.co',
 'Fabogo',
 'Flickstree',
 'Design Cafe',
 'Innoviti',
 'VDeliver',
 'Bottr.me',
 'Arcatron',
 'QwikSpec',
 'Vayana',
 'MObiquest',
 'Ambee',
 'Ideal Insurance',
 'Hypernova Interactive',
 'Rentomojo',
 'AirCTO',
 'Playablo',
 'Trupay',
 'Brick2Wall',
 'FableStreet',
 'Monsoon Fintech',
 'MonkeyBox',
 'Byju\\\\xe2\\\\x80\\\\x99s',
 'Creator\\\\xe2\\\\x80\\\\x99s Gurukul',
 'Fab Hotels',
 'ThinkerBell',
 'Jhakaas',
 'BigStylist',
 'Gympik.com',
 'Tripeur',
 'RentOnGo',
 'Goomo',
 'MaxMyWealth',
 'Spinny',
 'Healthbuds',
 'Ftcash',
 'BHIVE Workspace',
 'wayForward',
 'GyanDhan',
 'GrowFitter',
 'Stratfit',
 'Multiplier Solutions',
 'ABI Health',
 'Stockal',
 'Guidoo',
 'eSahai.in',
 'Loanmeet',
 'LendingKart',
 'Boxx.ai',
 'PeeSafe.in',
 'Vista Rooms',
 'CoverFox',
 'HyperTrack',
 'Goodera',
 'Ola',
 'Vanitycask',
 'MrNeeds',
 'MoneyTap',
 'Goodbox',
 'PortDesk',
 'EdgeFx',
 'HealthIntel',
 'Unbxd',
 'DarwinBox',
 'ForeverShop',
 'Insider.in',
 'Grow Fit',
 'Fabulyst',
 'mSwipe',
 'OneAssist',
 'Julia Computing',
 'Explore Life traveling',
 'Loantap',
 'Voxweb',
 'HUG Innovations',
 'V Resorts',
 'Stashfin',
 'Formcept',
 'Spares Hub',
 'FiTraQ',
 'Niki.ai',
 'Fitpass',
 'ZingHR',
 'Tagos Design',
 'UrbanClap',
 'Ace2three',
 'Innovapptive',
 '4tigo',
 'SMECorner',
 'ZippServe',
 'HealthMir',
 'Uactive',
 'i-lend',
 'Good Methods Global',
 'Balance App',
 'YepMe',
 'Nightstay',
 'Devourin',
 'MyGreens',
 'Curie Labs',
 'Uncanny Vision',
 'Sequretek',
 'Lucideus',
 'Vidooly',
 'Shopclues',
 'Fourth Ambit',
 'Chymera VR',
 'Book My Diamond',
 'ION Energy',
 'Legal Raasta',
 'Log 9 Materials',
 'Remit Guru',
 'Aequm',
 'Zapty',
 'Vernacular.ai',
 'Telr',
 'Genie',
 'Paysense',
 'The Good Life',
 'PumpKart',
 'EzCred',
 'HealthSutra',
 'Delhivery',
 'ZipGrid',
 'TravelSpice',
 'Box8',
 'GenNext Students',
 'WhatsLoan',
 'Cube Consumer Services',
 'Wowflux',
 'Collateral Medical',
 'Loadshare',
 'SimpliLend',
 'Supr Daily',
 'SastaSundar',
 'Eruditus',
 'TestBook',
 'Healthcare at Home',
 'Tyre Express',
 'SmartCoin',
 'WayCool',
 'Perfios',
 'Whatfix',
 'ElastiRun',
 'Trukky',
 'Konsult App',
 'Credit Sudhaar',
 'DataWeave',
 'Medwell Ventures',
 'Mech Mocha',
 'Startup Buddy',
 'QorQI',
 'Twenty Two Motors',
 'WonderChef',
 'FastFox',
 'Omnify',
 'MergerWare',
 'Clovia',
 'Emiza',
 'HackerEarth',
 'Squadrun',
 'ScoutMyTrip',
 'SafetyKart',
 'WeAreHolidays',
 'Myly',
 'CrediHealth',
 'Navia Life Care',
 'Raw Pressery',
 'Snackible',
 'Be U Salons',
 'Simulanis',
 'Innefu Security Consulting',
 'Whodat',
 'Absentia VR',
 'IOTrek',
 'HolaChef',
 'Wooplr',
 'Video Ken',
 'Faasos',
 'Oyo Rooms',
 'Niramai',
 'The Office Pass',
 'Awfis',
 'Myra',
 'Flytxt',
 'Howdy Ventures',
 'StalkBuyLove',
 'ZipGo',
 'Scootsy',
 'Autobix',
 'eShiksha',
 'Sepalika',
 'Mintwalk',
 'Qriyo',
 'Belong',
 'Seenit',
 'Paalak',
 'Celes Care',
 'Karomi',
 'Red Carpet',
 'Kreate Konnect',
 'CreditMantri',
 'Lets Endorse',
 'Tydy',
 'Nactus',
 'Oho Shop',
 'Emojifi',
 'Paytm Marketplace',
 'iGenetics',
 'Juno Clinic',
 'Summerlabel',
 'PickMe',
 'Agrostar',
 'Zapr',
 'Data Resolve',
 'Book Servicing',
 'Blowhorn',
 'PipeCandy',
 'Parentune',
 'AppBrowzer',
 'MagicBricks',
 'PeeBuddy',
 'iOrderFresh',
 'Lavelle Networks',
 'PropertyShare',
 'MyDermacy',
 'LatestOne',
 'Frapperz',
 'mPaani',
 'ShilpMIS',
 'Fitso',
 'FarMart',
 'Airpay',
 'MyGlamm',
 'The Mons Co.',
 'Haqdarshak',
 'Ixigo',
 'Markets and Markets',
 'Bizom',
 'BabyonBoard',
 'Sport Flashes',
 'Wigzo',
 'DoneThing',
 'Zapyle',
 'Ithaka',
 'perpule',
 'Emflux Motors',
 'Klinic App',
 'Oriano Solar',
 'Rooter',
 'FalconBrick',
 'Clodura',
 'Stockroom.io',
 'iManageMyHotel',
 'Inner Hour',
 'Travel Triangle',
 'Wandertrails',
 'Zenatix',
 'Cartrade',
 'MindYourFleet',
 'Edurev',
 'Voonik',
 '1Crowd',
 '48East',
 'Redesyn',
 'Flutura',
 'Wassup',
 'Better Mortgage',
 'Nurturey',
 'Fyle',
 'GoBumpr',
 'CCAvenue',
 'Connaizen',
 'AirZaar',
 'Truebil',
 'YourStory',
 'Imaginate',
 'Aisle',
 'TownScript',
 'Leopetra',
 'Blood n Care',
 'Vebbler',
 'Lets Reap',
 'Oglas',
 'Staydobe',
 'Johari Shop',
 'NeoStencil',
 'TaxSutra',
 'TempoGo',
 'GoFynd',
 'Vow Car Clinic',
 'LearnTron',
 'MobiDent',
 'Yostra',
 'Leap India',
 'FreeCharge',
 'TicketNew',
 'Intelligence Node',
 'Securens',
 'Loan Frame',
 'DriveSkool',
 'LensKart',
 'InstaOffice',
 'Hansel.io',
 'Square Yards',
 'Roambee',
 'PaisaWapas',
 'iService',
 'SecururAX',
 'Leadburg',
 'ZoloStays',
 'Oi Media',
 'HipCouch',
 'Curiositi',
 'TinyStep',
 'Practo',
 'Ketchupp',
 'Hoopy',
 'Ezytruk',
 'Kratikal',
 'Direct Create',
 'Vahdam Teas',
 'Qwikspec',
 'PParke',
 'Weddingz.in',
 'Native Special',
 'Fitnapp',
 'Ethosh',
 'MessaGif',
 'SmartHi',
 'CRON Systems',
 'CueMath',
 'ChipperSage',
 'SelectJobs',
 'Khel Now',
 'NowFloats',
 'Lets Transport',
 'BetaOut',
 'Wishberry',
 'RML Agtech',
 'LoyaltyPrime',
 'InstaSafe',
 '99Games',
 'AirMed Labs',
 '99PerHour',
 'Kochi Post',
 'Intuit Things',
 'Cloudrino',
 'FabX',
 'Maptags',
 'YOLO Health',
 'Heads Up For Tails',
 'Register My Marriage',
 'SidQam',
 'India Lends',
 'Slide App',
 'Badiyajobs',
 'Streo',
 'TYGR',
 'Mr Hot Foods',
 'UrDoorStep',
 'Diro Labs',
 'THB',
 'LookAtMe',
 'Netree',
 'BookEventz',
 'Tailslife',
 'WealthApp',
 'Vehico',
 'Zest Money',
 'GoMechanic',
 'Stalk Buy Love',
 'Wittyparot',
 'NeuroEquilibrium',
 'Xseed Education',
 ...]

In [5]:
investor_name = df['Investors Name'].unique().tolist()

In [10]:
df[df['Startup Name']=='Mamaearth']

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN

In [9]:
df['Startup Name']

0                             BYJU’S
1                             Shuttl
2                          Mamaearth
3       https://www.wealthbucket.in/
4                             Fashor
                    ...
3039                      Printvenue
3040                        Graphene
3041                  Mad Street Den
3042                       Simplotel
3043                couponmachine.in
Name: Startup Name, Length: 3044, dtype: object

In [ ]:
# Investors

#Data cleaning

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [14]:
df = df.drop(columns=['Remarks'],inplace=True)

KeyError: "['Remarks'] not found in axis"

In [15]:
df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [16]:
df.set_index('Sr No',inplace=True)

In [92]:
df.rename(
    columns= {
        'Date dd/mm/yyyy':'date',
        'Startup Name':'startup',
        'Industry Vertical':'vertical',
        'Sub Vertical':'subvertical',
        'City  Location':'city',
        'Invertors Name':'investors',
        'Investmentntype':'round',
        'Amount in USD':'amount',

    },inplace=True
)

In [93]:
df.columns

Index(['date', 'startup', 'vertical', 'SubVertical', 'city', 'Investors Name',
       'InvestmentnType', 'amount'],
      dtype='object')

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3026 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1285 non-null   datetime64[ns]
 1   startup          3026 non-null   object
 2   vertical         2855 non-null   object
 3   SubVertical      2101 non-null   object
 4   city             2846 non-null   object
 5   Investors Name   3002 non-null   object
 6   InvestmentnType  3024 non-null   object
 7   amount           3026 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 212.8+ KB

In [95]:
df['amount']=df['amount'].fillna('0')

In [96]:
df['amount']=df['amount'].str.replace(',','')
# df['amount'] = df['amount'].str.replace('undisclosed','0')
# df['amount'] = df['amount'].str.replace('unknown','0')
# df['amount'] = df['amount'].str.replace('Undisclosed','0')
# df['amount'] = df['amount'].str.replace('NaN','0')



df['amount']

AttributeError: Can only use .str accessor with string values!

In [97]:
df = df[df['amount'].str.isdigit()]

AttributeError: Can only use .str accessor with string values!

In [98]:
df['amount']=df['amount'].astype('float')

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3026 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1285 non-null   datetime64[ns]
 1   startup          3026 non-null   object
 2   vertical         2855 non-null   object
 3   SubVertical      2101 non-null   object
 4   city             2846 non-null   object
 5   Investors Name   3002 non-null   object
 6   InvestmentnType  3024 non-null   object
 7   amount           3026 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 212.8+ KB

In [100]:
def to_inr(dollars):
    inr = dollars * 74.83
    return inr/10000000

In [101]:
to_inr(200000000)

1496.6

In [102]:
df['amount'] = df['amount'].apply(to_inr)

In [91]:
df

,date,startup,vertical,SubVertical,city,Investors Name,InvestmentnType,amount
Sr No,,,,,,,,
1,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,8.380255e-08
2,NaT,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,3.372380e-09
3,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,7.692596e-09
4,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,1.257038e-09
5,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,7.542229e-10
...,...,...,...,...,...,...,...,...
3040,NaT,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,1.885557e-09
3041,NaT,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,3.456855e-10
3042,NaT,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,6.285191e-10
3043,NaT,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,0.000000e+00
3044,NaT,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,5.866178e-11

In [107]:
df['date']

Sr No
1      2020-09-01
2             NaT
3      2020-09-01
4      2020-02-01
5      2020-02-01
          ...
3040          NaT
3041          NaT
3042          NaT
3043          NaT
3044          NaT
Name: date, Length: 3026, dtype: datetime64[ns]

ValueError: time data "05/072018" doesn't match format "%d/%m/%Y", at position 119. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [88]:
df['date']

Sr No
1      2020-09-01
2             NaT
3      2020-09-01
4      2020-02-01
5      2020-02-01
          ...
3040          NaT
3041          NaT
3042          NaT
3043          NaT
3044          NaT
Name: date, Length: 3026, dtype: datetime64[ns]

In [68]:
df['date']=df['date'].replace({'05/072018':'05/07/2018'})
df['date']

Sr No
1      2020-09-01
2             NaT
3      2020-09-01
4      2020-02-01
5      2020-02-01
          ...
3040          NaT
3041          NaT
3042          NaT
3043          NaT
3044          NaT
Name: date, Length: 3026, dtype: datetime64[ns]

ValueError: time data "01/07/015" doesn't match format "%d/%m/%Y", at position 873. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [83]:
df = df.replace({"date": {"01/07/015": "01/07/2015","12/05.2015": "12/05/2015"}})

In [87]:
df

,date,startup,vertical,SubVertical,city,Investors Name,InvestmentnType,amount
Sr No,,,,,,,,
1,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1496.600000
2,NaT,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,60.226132
3,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,137.379349
4,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,22.449000
5,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,13.469400
...,...,...,...,...,...,...,...,...
3040,NaT,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,33.673500
3041,NaT,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,6.173475
3042,NaT,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,11.224500
3043,NaT,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,0.000000
3044,NaT,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,1.047620

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3026 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1285 non-null   datetime64[ns]
 1   startup          3026 non-null   object
 2   vertical         2855 non-null   object
 3   SubVertical      2101 non-null   object
 4   city             2846 non-null   object
 5   Investors Name   3002 non-null   object
 6   InvestmentnType  3024 non-null   object
 7   amount           3026 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 212.8+ KB

In [106]:
df['date'].dt.year

Sr No
1       2020.0
2          NaN
3       2020.0
4       2020.0
5       2020.0
         ...
3040       NaN
3041       NaN
3042       NaN
3043       NaN
3044       NaN
Name: date, Length: 3026, dtype: float64